### ISSUE TITLE
Page does not exist

### ISSUE THREAD

**Issue by 1466758326** [onera/olcmr#1]
Hello, I am Liang Yapeng from Wuhan University. I am very interested in your work on GitHub, but I encounter issues connecting when trying to clone. I would like to seek some advice on this.
-----
git clone https://gitlab.com/stage-qserdel/olcmr --recurse-submodules
-----
https://gitlab.com/stage-qserdel/olcmr，Page does not exist。

**Comment by qserdel** [comment]
Hello, thanks for your interest in our work. This issue has been corrected, you should be able to clone the repository now.

**Comment by 1466758326** [comment]
Line 93 in the olcmr_newer_college.launch.py file parameters=[{'calibration': velodyne_calibration_file,
                      'min_range': 0.8,
                      'max_range': 50.0,
                      'view_direction': 0.0,
                      'view_width': 5.23598775598}], velodyne_calibration_file in is not defined. What is the specific function of the velodyne_calibration_file file and where can it be obtained？

**Comment by 1466758326** [comment]
ament_index_python.packages.PackageNotFoundError: "package 'scanmatcher' not found, searching: ['/media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam/install/olcmr_pkg', '/media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam/install/cs_tools', '/opt/ros/foxy']"

**Comment by qserdel** [comment]
Both issues should be handled now. Don't hesitate to keep pointing issues out. 
Thank you for helping us debugging and improving this repository !

**Comment by 1466758326** [comment]
lyp@lyp99:/media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam$ colcon build --symlink-install
Starting >>> lidarslam_msgs
Starting >>> ndt_omp_ros2
Starting >>> cs_tools                                        
Finished <<< ndt_omp_ros2 [0.77s]                                       
Finished <<< cs_tools [0.79s]                                        
Starting >>> olcmr_pkg
Finished <<< lidarslam_msgs [1.39s]                                  
Starting >>> graph_based_slam
Starting >>> scanmatcher                                           
Finished <<< olcmr_pkg [0.95s]                                     
--- stderr: graph_based_slam                                                                           
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib/cmake/g2o/g2oConfig.cmake:4 (find_dependency)
  CMakeLists.txt:33 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

/media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam/src/lidarslam_ros2/graph_based_slam/src/graph_based_slam_component.cpp: In member function ‘void graphslam::GraphBasedSlamComponent::doPoseAdjustment(lidarslam_msgs::msg::MapArray, bool)’:
/media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam/src/lidarslam_ros2/graph_based_slam/src/graph_based_slam_component.cpp:272:10: error: ‘make_unique’ is not a member of ‘g2o’; did you mean ‘std::make_unique’?
  272 |     g2o::make_unique<g2o::LinearSolverEigen<g2o::BlockSolver_6_3::PoseMatrixType>>();
      |          ^~~~~~~~~~~
In file included from /usr/include/c++/9/memory:80,
                 from /opt/ros/foxy/include/rclcpp/rclcpp.hpp:144,
                 from /media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam/src/lidarslam_ros2/graph_based_slam/include/graph_based_slam/graph_based_slam_component.h:42,
                 from /media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam/src/lidarslam_ros2/graph_based_slam/src/graph_based_slam_component.cpp:1:
/usr/include/c++/9/bits/unique_ptr.h:868:5: note: ‘std::make_unique’ declared here
  868 |     make_unique(_Args&&...) = delete;
      |     ^~~~~~~~~~~
/media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam/src/lidarslam_ros2/graph_based_slam/src/graph_based_slam_component.cpp:272:81: error: expected primary-expression before ‘>’ token
  272 | <g2o::LinearSolverEigen<g2o::BlockSolver_6_3::PoseMatrixType>>();
      |                                                             ^~

/media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam/src/lidarslam_ros2/graph_based_slam/src/graph_based_slam_component.cpp:272:84: error: expected primary-expression before ‘)’ token
  272 | o::LinearSolverEigen<g2o::BlockSolver_6_3::PoseMatrixType>>();
      |                                                             ^

/media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam/src/lidarslam_ros2/graph_based_slam/src/graph_based_slam_component.cpp:274:10: error: ‘make_unique’ is not a member of ‘g2o’; did you mean ‘std::make_unique’?
  274 |     g2o::make_unique<g2o::BlockSolver_6_3>(std::move(linear_solver)));
      |          ^~~~~~~~~~~
In file included from /usr/include/c++/9/memory:80,
                 from /opt/ros/foxy/include/rclcpp/rclcpp.hpp:144,
                 from /media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam/src/lidarslam_ros2/graph_based_slam/include/graph_based_slam/graph_based_slam_component.h:42,
                 from /media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam/src/lidarslam_ros2/graph_based_slam/src/graph_based_slam_component.cpp:1:
/usr/include/c++/9/bits/unique_ptr.h:868:5: note: ‘std::make_unique’ declared here
  868 |     make_unique(_Args&&...) = delete;
      |     ^~~~~~~~~~~
/media/lyp/datadiskone/ubuntu_ros/ros_ws/Colored_Mesh_olcmr/olcmr_slam/src/lidarslam_ros2/graph_based_slam/src/graph_based_slam_component.cpp:274:42: error: expected primary-expression before ‘>’ token
  274 |     g2o::make_unique<g2o::BlockSolver_6_3>(std::move(linear_solver)));
      |                                          ^
make[2]: *** [CMakeFiles/graph_based_slam_component.dir/build.make:63：CMakeFiles/graph_based_slam_component.dir/src/graph_based_slam_component.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:107：CMakeFiles/graph_based_slam_component.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2
---
Failed   <<< graph_based_slam [16.2s, exited with code 2]
Aborted  <<< scanmatcher [52.5s]                                  

Summary: 4 packages finished [55.0s]
  1 package failed: graph_based_slam
  1 package aborted: scanmatcher
  2 packages had stderr output: graph_based_slam scanmatcher
  1 package not processe

-------------------------------------------------------------
Is this related to the version of ros? I did not install galactic, only the foxy version. G2o was installed according to the warehouse. I have not installed g2o before.

**Comment by qserdel** [comment]
Hello, this is a g2o related problem that has been encountered and answered in the following issue: 
[https://github.com/RainerKuemmerle/g2o/issues/719](https://github.com/RainerKuemmerle/g2o/issues/719 )
Let me know if you manage to solve it !
