### ISSUE TITLE
I encounter some trouble when try to install this project 

### ISSUE THREAD

**Issue by wuyukun-tong** [onera/olcmr#4]
when I run "colcon build --symlink-install", I came across these error as follow: error: ‘make_unique’ is not a member of ‘g2o’; did you mean ‘std::make_unique’?  g2o::make_unique<g2o::LinearSolverEigen<g2o::BlockSolver_6_3::PoseMatrixType>>();
error: expected primary-expression before ‘>’ token
  272 |     g2o::make_unique<g2o::LinearSolverEigen<g2o::BlockSolver_6_3::PoseMatrixType>>();
error: expected primary-expression before ‘)’ token
  272 |     g2o::make_unique<g2o::LinearSolverEigen<g2o::BlockSolver_6_3::PoseMatrixType>>();
error: ‘make_unique’ is not a member of ‘g2o’; did you mean ‘std::make_unique’?
  274 |     g2o::make_unique<g2o::BlockSolver_6_3>(std::move(linear_solver)));
      |          ^~~~~~~~~~~
error: expected primary-expression before ‘>’ token
  274 |     g2o::make_unique<g2o::BlockSolver_6_3>(std::move(linear_solver)));

**Comment by qserdel** [comment]
Hello, this is a g2o related problem that has been encountered and answered in the following issue:
https://github.com/RainerKuemmerle/g2o/issues/719

**Comment by wuyukun-tong** [comment]
thank you for your replay



---- Replied Message ----
| From | Quentin ***@***.***> |
| Date | 03/26/2024 00:25 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [onera/olcmr] I encounter some trouble when try to install this project (Issue #4) |

Hello, this is a g2o related problem that has been encountered and answered in the following issue:
RainerKuemmerle/g2o#719
